name: Test Python backend

on: [push]

env:
  AWS_DEFAULT_REGION: eu-west-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest
